<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Datamodel_Tests</RootNamespace>
    <AssemblyName>Datamodel.NET-Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Resources\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Resources\vmap.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Datamodel.NET\Datamodel.NET.csproj" />
    <ProjectReference Include="..\Tests.VMAP\Tests.VMAP.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.65.0" />
  </ItemGroup>

  <ItemGroup>
  	<ProjectReference Include="..\ElementFactoryGenerator\ElementFactoryGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
