<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Version>0.2</Version>
		<Nullable>enable</Nullable>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IsRoslynComponent>true</IsRoslynComponent>
		<PackageId>KeyValues2.ElementFactoryGenerator</PackageId>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Authors>Tom Edwards, ValveResourceFormat contributors</Authors>
		<Copyright>Copyright (c) 2013 Tom Edwards and ValveResourceFormat contributors</Copyright>
		<Description>Source generator for reflection-based Element deserialisation in Datamodel.NET (KeyValues2).</Description>
		<PackageProjectUrl>https://github.com/ValveResourceFormat/Datamodel.NET</PackageProjectUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.1.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.3" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

</Project>
