<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Datamodel.NET\Datamodel.NET.csproj" />
    <ProjectReference Include="..\Tests.VMAP\Tests.VMAP.csproj" />
  </ItemGroup>

</Project>
